InstallationCheck minor change.

diff --git a/OSX_Resources/InstallationCheck b/OSX_Resources/InstallationCheck
--- a/OSX_Resources/InstallationCheck
+++ b/OSX_Resources/InstallationCheck
@@ -10,14 +10,14 @@ then
     if arch | grep "i386"
     then
 	# You have an intel mac error message
-	exit 115
+	exit 116
     else
 	# PowerPC message
-	exit 116
+	exit 117
     fi
 fi
 
-# Check to make sure the computer is running 10.5.7 or later.
+# Check to make sure the computer is running 10.5 or later.
 
 version=`uname -a | sed 's/.*Darwin Kernel Version \([0-9.]*\):.*/\1/'`
 major=`echo $version | sed 's/\([0-9]\)\.\([0-9]\)\.\([0-9]\)/\1/'`
@@ -35,6 +35,7 @@ fi
 if test -z "`dap-config --version 2> /dev/null`"
 then
     # fail and display message 17
+    # echo "can't find dap-config\n"
     exit 113
 fi
 
@@ -45,8 +46,8 @@ minor=`echo $version | sed 's/\([0-9]\)\.\([0-9]\)\.\([0-9]\)/\2/'`
 
 if test $major -lt 3 -o $major -eq 3 -a $minor -lt 9
 then
-    #echo "DAP requirement failed\n"
-    exit 113
+   # echo "DAP requirement failed\n"
+    exit 114
 fi
 
 # Now check for bes: first check that we can run the config script, then
@@ -54,8 +55,9 @@ fi
 
 if test -z "`bes-config --version 2> /dev/null`"
 then
-    # bes does not need to be installed, so just exit
-    exit 0
+    # Don't we need the BES to place the shared obj?
+    # echo "BES not installed.\n"
+    exit 115
 fi
 
 version=`bes-config --version | sed 's/bes \([0-9.]*\)/\1/'`
@@ -66,8 +68,8 @@ minor=`echo $version | sed 's/\([0-9]\)\.\([0-9]\)\.\([0-9]\)/\2/'`
 if test $major -lt 3 -o $major -eq 3 -a $minor -lt 7
 then
     # echo "BES requirement failed\n"
-    # fail and display message 18
-    exit 114
+    # fail and display message 19
+    exit 115
 fi
 
 exit 0
